In [1]:
import numpy as np

In [3]:
list_ = [ '1' , '2', '3', '4', '5']
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

In [4]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [6]:
list_

['1', '2', '3', '4', '5']

In [8]:
# The difference is in their type.
type(list_)


list

In [9]:
type(array_list)

numpy.ndarray

In [10]:
array_list.dtype

dtype('<U1')

In [ ]:
#dtype of list is not defined

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

In [12]:
list_

['1', '2', '3', '4', '5']

In [13]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [17]:
for i in list_:
    print('Data type of element',i, ' is ', type(i))

Data type of element 1  is  <class 'str'>
Data type of element 2  is  <class 'str'>
Data type of element 3  is  <class 'str'>
Data type of element 4  is  <class 'str'>
Data type of element 5  is  <class 'str'>


In [18]:
for i in array_list:
    print('Data type of element',i, ' is ', type(i))

Data type of element 1  is  <class 'numpy.str_'>
Data type of element 2  is  <class 'numpy.str_'>
Data type of element 3  is  <class 'numpy.str_'>
Data type of element 4  is  <class 'numpy.str_'>
Data type of element 5  is  <class 'numpy.str_'>


Q3. Considering the following changes in the variable, array_list:

Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [19]:
array_list = np.array(object = list_, dtype = int)

In [20]:
array_list

array([1, 2, 3, 4, 5])

In [21]:
list_

['1', '2', '3', '4', '5']

In [23]:
# Yes there is difference in the data typr of the elements present in both the variables list_ and ayyay_list
# the elements in array_list will be explicitly converted to integers.

In [24]:
print("Dta types of elements of list_ are: ")

for i in list_:
    print(type(i))

Dta types of elements of list_ are: 
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [25]:
print("Dta types of elements of array_list are: ")

for i in array_list:
    print(type(i))

Dta types of elements of array_list are: 
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>
<class 'numpy.int64'>


In [26]:
# previousely it was a string

In [27]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [28]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [29]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [30]:
np.shape(num_array)

(2, 3)

In [31]:
np.size(num_array)

6

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [34]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Q6. Create an identity matrix of shape (5,5) using numpy functions?
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [35]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])